#ifndef __FUNDDOM_CORE_H__
#define __FUNDDOM_CORE_H__

/*****************************************************************************
 * funddom_core -- the limit-trap kernel of funddom.c, as a C API that C++ can
 * call.  The interactive program needs this mathematics to draw limit traps at
 * an arbitrary renormalization point; funddom.c already implements it, and it
 * would be a mistake to keep a second, slower copy in C++.
 *
 * The implementation IS funddom.c, compiled a second time without
 * -DFUNDDOM_MAIN (which is what selects the command-line driver).  So there is
 * exactly one copy of the mathematics, and the CLI and the GUI cannot drift
 * apart.  See the makefile's funddom_core.o rule.
 *
 * Deliberately POD only -- no `double complex`, no `std::complex` -- because
 * C99's complex type is not a C++ type and a header containing one cannot be
 * included from C++ at all.  Every complex quantity is passed as a pair of
 * doubles.
 *
 * THE SOLVER IS A SINGLETON.  funddom.c keeps its ball set, grid index and
 * derived constants in file statics, so there is one solver at a time and it is
 * not thread safe.  Call fd_solver_init, use it, then fd_solver_free.  That is
 * adequate for a single-threaded GUI and avoids a risky reentrancy refactor of
 * numeric code; if you ever need two at once, that refactor is the next step.
 *
 * Typical use:
 *
 *     fd_core c;
 *     fd_core_builtin("s0", &c);                  // or fd_core_from_lm("-+", "-", 0, &c)
 *     fd_solver_init(&c, balls3, nballs);         // balls3 from ifs::trap_like_balls_many
 *     fd_info info; fd_solver_info(&info);        // info.rho_max sizes your raster
 *     int level = fd_level(C_re, C_im, cmax);     // -1 = not certified up to cmax
 *     fd_solver_free();
 * ***************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif

/* The renormalization data of a landmark point: sigma with words u,v of length a
   and s,t of length b such that pi(u s^inf, sigma) = pi(v t^inf, sigma).
   Delta = p_u - p_v, and P is the coincidence polynomial, so P(sigma) = 0. */
typedef struct {
  double sigma_re, sigma_im;
  int    a, b;
  double Delta_re, Delta_im;
  double Pp_re, Pp_im;              /* P'(sigma) */
} fd_core;

/* One enumerated landmark point.  `spec` is a ready-to-reuse "lm:<A>:<B>:<k>"
   string, accepted both by fd_core_from_lm and by funddom's command line. */
typedef struct {
  double sigma_re, sigma_im;
  int    a, b, deg;
  char   spec[48];
} fd_landmark;

/* Constants a caller needs in order to choose a sensible window of C. */
typedef struct {
  double R_Gamma;                   /* radius of the disc containing the difference set */
  double Y0_re, Y0_im;              /* Y(0) */
  double dYdC_re, dYdC_im;          /* Y(C) = Y0 + C dY/dC */
  double rho_max;                   /* largest useful |C|: (R_Gamma - |Y0|)/|dY/dC|.
                                       Beyond this every sampled C is out of range and
                                       the coverage figure is vacuous, not zero. */
  /* b*log(1/|sigma|): the height, in log|C|, of one fundamental domain of the
     elliptic curve E_sigma (the quotient of C^* by the group generated by
     sigma^b).  Spelling that quotient with a slash inside a block comment would
     close the comment, so it is spelled out. */
  double period_height;
  int    nballs;
} fd_info;

/*---------------------------------------------------------- getting a core ---*/

/* "s0", "s1" or "hex".  Returns 0, or -1 if the name is unknown. */
int fd_core_builtin(const char *name, fd_core *out);

/* A landmark point from the sign strings of A and B over {'-','0','+'}, meaning
   coefficients -1, 0, +1; A must begin '-'.  `pick` selects among the admissible
   roots (those with 1/2 < |sigma| < 1 and Im sigma > 0).  Returns the NUMBER of
   admissible roots on success, 0 if there are none, -1 if A or B is malformed,
   -2 if `pick` is out of range. */
int fd_core_from_lm(const char *A, const char *B, int pick, fd_core *out);

/* Enumerate the landmark points of complexity a+b <= N, in increasing a+b.
   Writes at most maxout of them and returns the count, or -1 if N is out of range.
   A return value EQUAL to maxout means the list was truncated -- there may be more.
   Size the buffer accordingly: there are 1, 18, 99, 533, 2421, 10958 and 46201
   landmarks for N = 3..9, and since the CKW hexahole first appears at a+b = 9, a
   caller that wants it needs room for all 46201.  Cost grows like (N-1)*3^(N-1)
   polynomials: N=8 is under a second, N=9 a few seconds, N=10 about sixteen. */
int fd_landmarks(int N, fd_landmark *out, int maxout);

/*-------------------------------------------------------------- the solver ---*/

/* balls3 holds (center_re, center_im, radius) triples for the trap-like balls at
   sigma, in SCHOTTKY's normalization f(x)=zx, g(x)=z(x-1)+1 -- exactly what
   certify_arc's dumptlb/dumptlbmany print and what ifs::trap_like_balls_many
   returns.  The 2/(1-sigma) conjugation into this file's normalization is
   applied HERE, so that no caller can forget it; getting that wrong yields a
   plausible near-zero coverage rather than an error.
   Returns 0, or -1 if nballs < 1 or allocation fails. */
int  fd_solver_init(const fd_core *c, const double *balls3, int nballs);
void fd_solver_free(void);
void fd_solver_info(fd_info *out);

/* The least tail length c <= cmax at which C admits a certified limit trap, or
   -1 if none does.  This is the per-pixel query. */
int fd_level(double C_re, double C_im, int cmax);

/* Whether Y(C) survives `depth` levels of the difference-set IFS: an
   over-approximation of "C lies in T_sigma at all".  0 or 1. */
int fd_survives(double C_re, double C_im, int depth);

#ifdef __cplusplus
}
#endif

#endif
